version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www/${COMPOSE_PROJECT_NAME}
    container_name: ${COMPOSE_PROJECT_NAME}-app
    hostname: ${COMPOSE_PROJECT_NAME}-app
    working_dir: /var/www/${COMPOSE_PROJECT_NAME}

  nginx:
    image: nginx:1.21.6
    volumes:
      - ./:/var/www/${COMPOSE_PROJECT_NAME}
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    hostname: ${COMPOSE_PROJECT_NAME}-nginx
    working_dir: /var/www/${COMPOSE_PROJECT_NAME}
    ports:
      - "81:80"

  mysql:
    image: mysql:8.0.28
    volumes:
      - db:/var/lib/mysql
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    hostname: ${COMPOSE_PROJECT_NAME}-mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"

volumes:
  db: